# Generated by Django 4.1.2 on 2022-10-10 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0004_surveyuseranswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestionalternative',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='survey_alternatives', to='survey.survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyuseranswer',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answer', to='survey.survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyuseranswer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
